### ISSUE TITLE
Be able to deposit and withdraw

### ISSUE THREAD

**Issue by hungyanbin** [hungyanbin/YBAccouting#1]
## TODO 

- [x] List view for transaction history
- [x] load data from repository
- [x] Add data to repository
- [x] DI framework
- [x] Service layer
- [x] check database is run on IO thread or not
